#!/bin/bash
set -e

echo "Hello gh-depandabot!"

# Determine if an executable is in the PATH
if ! type -p xargs >/dev/null; then
  echo "xargs not found on the system" >&2
  exit 1
fi

gh pr list -R jusio/gh-dependabot-test --label dependencies --jq '.[] | .url' --json 'url' | xargs -I % gh pr review % -a -b "@dependabot merge"
